-- Migration: Create product_availability table for managing product availability per channel
-- This allows controlling which products are available in different apps/channels (e.g., cloud_console)

-- Create the product_availability table
CREATE TABLE IF NOT EXISTS product_availability (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id UUID NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    channel VARCHAR(50) NOT NULL DEFAULT 'cloud_console',
    is_available BOOLEAN NOT NULL DEFAULT true,
    available_from TIMESTAMPTZ NULL,  -- NULL means available from the beginning
    available_until TIMESTAMPTZ NULL, -- NULL means available forever
    sort_order INTEGER NULL,          -- For display ordering in the channel
    notes TEXT NULL,                   -- Optional notes about availability
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NULL,
    deleted_at TIMESTAMPTZ NULL,

    -- Ensure unique product per channel (only one active record per product/channel)
    CONSTRAINT unique_product_channel UNIQUE (product_id, channel, deleted_at)
);

-- Create indexes for common queries
CREATE INDEX idx_product_availability_channel ON product_availability(channel) WHERE deleted_at IS NULL;
CREATE INDEX idx_product_availability_product ON product_availability(product_id) WHERE deleted_at IS NULL;
CREATE INDEX idx_product_availability_dates ON product_availability(available_from, available_until) WHERE deleted_at IS NULL AND is_available = true;

-- Enable RLS
ALTER TABLE product_availability ENABLE ROW LEVEL SECURITY;

-- Create policy for authenticated users (adjust based on your auth setup)
CREATE POLICY "Allow all operations for authenticated users" ON product_availability
    FOR ALL
    USING (true)
    WITH CHECK (true);

-- Add comment to table
COMMENT ON TABLE product_availability IS 'Manages product availability per channel/app (e.g., cloud_console, partner_portal)';
COMMENT ON COLUMN product_availability.channel IS 'The channel/app identifier (e.g., cloud_console, partner_portal)';
COMMENT ON COLUMN product_availability.available_from IS 'When the product becomes available (NULL = from beginning)';
COMMENT ON COLUMN product_availability.available_until IS 'When the product stops being available (NULL = forever)';

-- Example query to get currently available products for cloud console:
-- SELECT p.*, pa.sort_order
-- FROM products p
-- INNER JOIN product_availability pa ON p.id = pa.product_id
-- WHERE pa.channel = 'cloud_console'
--   AND pa.is_available = true
--   AND pa.deleted_at IS NULL
--   AND p.deleted_at IS NULL
--   AND p.is_active = true
--   AND (pa.available_from IS NULL OR pa.available_from <= NOW())
--   AND (pa.available_until IS NULL OR pa.available_until >= NOW())
-- ORDER BY pa.sort_order NULLS LAST, p.name;
